# run `cargo make example` in /home of a container offa ../../Dockerfile

[env]
RUSTFLAGS = "-C target-feature=-crt-static"
EXAMPLE_ZIP_FILE_NAME = { value = "example.zip", condition = { env_not_set = ["EXAMPLE_ZIP_FILE_NAME"] } }

[tasks.setup-mac.mac]
script = [
'''
brew install FiloSottile/musl-cross/musl-cross # takes 4ever
rustup target add x86_64-unknown-linux-musl
'''
]

[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.build.mac]
env = { PKG_CONFIG_ALLOW_CROSS=true, CARGO_BUILD_TARGET="x86_64-unknown-linux-musl", CC_x86_64_unknown_linux_musl="x86_64-linux-musl-gcc", CXX_x86_64_unknown_linux_musl="x86_64-linux-musl-g++", CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_LINKER="x86_64-linux-musl-gcc" }

[tasks.peep]
script = [
'''
ls ./target/x86_64-unknown-linux-musl/release
'''
]

[tasks.bundle]
command = "zip"
args = ["-mj", "./${RUNTIME_ZIP_FILE_NAME}", "./target/x86_64-unknown-linux-musl/release/crab-lambda-easy-example.so"]

[tasks.example]
dependencies = ["format", "clean", "build", "peep", "bundle"]