name: rm old artifacts

on:
  schedule:
    # first day in the month @04:19am
    - cron: '19 4 1 * *'

jobs:
  rm_old_artifacts:
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
      - uses: c-hive/gha-remove-artifacts@v1.2.0
        with:
          age: '1 month'
